var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/coupons/use/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01q672i._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0d29_tg.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fs_z1a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0u2uxnw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_coupons_layout_tsx_1s-7xzq._.js")
R.c("server/chunks/ssr/_next-internal_server_app_coupons_use_page_actions_1n2yn72.js")
R.m(98878)
module.exports=R.m(98878).exports
