var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/hotels/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bx1qui._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xh0xdx.js")
R.c("server/chunks/ssr/[root-of-the-server]__20zwt28._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ru97ib._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0u2uxnw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_hotels_page_actions_1_mhml3.js")
R.m(63729)
module.exports=R.m(63729).exports
