// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/coupons" | "/admin/hotels" | "/admin/users" | "/bookings" | "/contact" | "/coupons" | "/coupons/use" | "/dashboard" | "/faq" | "/hotel/bookings" | "/hotel/dashboard" | "/hotel/verify" | "/hotels" | "/hotels/[id]" | "/login" | "/pricing" | "/privacy" | "/register" | "/subscription" | "/terms"
type AppRouteHandlerRoutes = "/api" | "/api/admin/coupons" | "/api/admin/dashboard" | "/api/admin/hotels" | "/api/admin/users" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/coupons" | "/api/coupons/use" | "/api/cron/expire-coupons" | "/api/hotel/bookings" | "/api/hotel/cancel" | "/api/hotel/checkin" | "/api/hotel/confirm-payment" | "/api/hotel/no-show" | "/api/hotel/reserve" | "/api/hotel/verify" | "/api/hotels" | "/api/hotels/[id]" | "/api/subscription"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/bookings" | "/coupons" | "/dashboard" | "/hotel" | "/subscription"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/coupons": {}
  "/admin/hotels": {}
  "/admin/users": {}
  "/api": {}
  "/api/admin/coupons": {}
  "/api/admin/dashboard": {}
  "/api/admin/hotels": {}
  "/api/admin/users": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/coupons": {}
  "/api/coupons/use": {}
  "/api/cron/expire-coupons": {}
  "/api/hotel/bookings": {}
  "/api/hotel/cancel": {}
  "/api/hotel/checkin": {}
  "/api/hotel/confirm-payment": {}
  "/api/hotel/no-show": {}
  "/api/hotel/reserve": {}
  "/api/hotel/verify": {}
  "/api/hotels": {}
  "/api/hotels/[id]": { "id": string; }
  "/api/subscription": {}
  "/bookings": {}
  "/contact": {}
  "/coupons": {}
  "/coupons/use": {}
  "/dashboard": {}
  "/faq": {}
  "/hotel": {}
  "/hotel/bookings": {}
  "/hotel/dashboard": {}
  "/hotel/verify": {}
  "/hotels": {}
  "/hotels/[id]": { "id": string; }
  "/login": {}
  "/pricing": {}
  "/privacy": {}
  "/register": {}
  "/subscription": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/bookings": never
  "/coupons": never
  "/dashboard": never
  "/hotel": never
  "/subscription": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
