var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1q_bfa_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1kb7r6o.js")
R.c("server/chunks/ssr/[root-of-the-server]__20zwt28._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ru97ib._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0u2uxnw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_0gttrt6._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_page_actions_1mcickz.js")
R.m(51687)
module.exports=R.m(51687).exports
